// User list dropdown items types:
export enum UserListDropdownItemType {
  OPTION = 'USER_LIST_DROPDOWN_OPTION',
  SEPARATOR = 'USER_LIST_DROPDOWN_SEPARATOR',
  FIXED_STRUCTURE_INFORMATION = 'USER_LIST_DROPDOWN_FIXED_STRUCTURE_INFORMATION',
  CONTENT_FUNCTION_STRUCTURE_INFORMATION = 'USER_LIST_DROPDOWN_CONTENT_FUNCTION_STRUCTURE_INFORMATION',
  TITLE_ACTION = 'USER_LIST_DROPDOWN_TITLE_ACTION',
}

export enum UserListDropdownSeparatorPosition {
  BEFORE = 'BEFORE_DEFAULT_ITEMS',
  AFTER = 'AFTER_DEFAULT_ITEMS',
}
