export enum LayoutPresentationAreaUiDataNames {
  CURRENT_ELEMENT = 'CURRENT_ELEMENT',
}

export enum UiLayouts {
  PINNED_SHARED_NOTES = 'PINNED_SHARED_NOTES',
  EXTERNAL_VIDEO = 'EXTERNAL_VIDEO',
  SCREEN_SHARE = 'SCREEN_SHARE',
  WHITEBOARD = 'WHITEBOARD',
  GENERIC_CONTENT = 'GENERIC_CONTENT',
}
