export enum LayoutPresentatioAreaUiDataNames {
  CURRENT_ELEMENT = 'CURRENT_ELEMENT',
}

export enum UiLayouts {
  PINNED_SHARED_NOTES = 'PINNED_SHARED_NOTES',
  EXTERNAL_VIDEO = 'EXTERNAL_VIDEO',
  SCREEN_SHARE = 'SCREEN_SHARE',
  ONLY_PRESENTATION = 'ONLY_PRESENTATION',
  GENERIC_COMPONENT = 'GENERIC_COMPONENT',
}
