// Presentation toolbar items types:
export enum PresentationType {
    PRESENTATION_TOOLBAR_BUTTON = 'PRESENTATION_TOOLBAR_BUTTON',
    PRESENTATION_TOOLBAR_LOADING = 'PRESENTATION_TOOLBAR_LOADING',
}
