// Presentation toolbar items types:
export enum PresentationType {
    PRESENTATION_TOOLBAR_BUTTON = 'PRESENTATION_TOOLBAR_BUTTON',
    PRESENTATION_TOOLBAR_SPINNER = 'PRESENTATION_TOOLBAR_SPINNER',
    PRESENTATION_TOOLBAR_SEPARATOR = 'PRESENTATION_TOOLBAR_SEPARATOR',
}
