export enum LayoutEnum {
  CHANGE_ENFORCED_LAYOUT = 'CHANGE_ENFORCED_LAYOUT',
}

export enum ChangeEnforcedLayoutTypeEnum {
  CUSTOM_LAYOUT = 'CUSTOM_LAYOUT',
  SMART_LAYOUT = 'SMART_LAYOUT',
  PRESENTATION_FOCUS = 'PRESENTATION_FOCUS',
  VIDEO_FOCUS = 'VIDEO_FOCUS',
  CAMERAS_ONLY = 'CAMERAS_ONLY',
  PRESENTATION_ONLY = 'PRESENTATION_ONLY',
  PARTICIPANTS_AND_CHAT_ONLY = 'PARTICIPANTS_AND_CHAT_ONLY',
  MEDIA_ONLY = 'MEDIA_ONLY',
}
