export enum LayoutEnum {
  CHANGE_ENFORCED_LAYOUT = 'CHANGE_ENFORCED_LAYOUT',
  SET_ENFORCED_LAYOUT = 'SET_ENFORCED_LAYOUT',
}

export enum EnforcedLayoutTypeEnum {
  CUSTOM_LAYOUT = 'CUSTOM_LAYOUT',
  SMART_LAYOUT = 'SMART_LAYOUT',
  PRESENTATION_FOCUS = 'PRESENTATION_FOCUS',
  VIDEO_FOCUS = 'VIDEO_FOCUS',
  CAMERAS_ONLY = 'CAMERAS_ONLY',
  PRESENTATION_ONLY = 'PRESENTATION_ONLY',
  PARTICIPANTS_AND_CHAT_ONLY = 'PARTICIPANTS_AND_CHAT_ONLY',
  MEDIA_ONLY = 'MEDIA_ONLY',
}

export const ChangeEnforcedLayoutTypeEnum = EnforcedLayoutTypeEnum;

export type ChangeEnforcedLayoutTypeEnum = EnforcedLayoutTypeEnum;
