export enum SidekickAreaOptionsEnum {
  RENAME_GENERIC_CONTENT_MENU = 'RENAME_GENERIC_CONTENT_SIDEKICK_AREA_MENU',
  RENAME_GENERIC_CONTENT_SECTION = 'RENAME_GENERIC_CONTENT_SIDEKICK_AREA_SECTION',
  SET_GENERIC_CONTENT_BADGE = 'SET_GENERIC_CONTENT_SIDEKICK_AREA_BADGE',
  REMOVE_GENERIC_CONTENT_BADGE = 'REMOVE_GENERIC_CONTENT_SIDEKICK_AREA_BADGE'
}
